version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    image: andr2ei/taski_backend:latest
    env_file: .env
    volumes:
      - media:/app/media/
      - static:/backend_static/
    depends_on:
      - db
  frontend:
    image: andr2ei/taski_frontend:latest
    env_file: .env
    volumes:
      - static:/frontend_static/
    depends_on:
      - backend
  gateway:
    image: andr2ei/taski_gateway:latest
    env_file: .env
    ports:
      - 9090:80
    volumes:
      - media:/var/www/default/media/
      - static:/staticfiles/
    depends_on:
      - frontend
